### ISSUE TITLE
Implement optional api-key and optional base-url

### ISSUE THREAD

**Issue by lilyhuang-github** [arilloid/addcom#3]
Changing it form the groq client to openai client might help with this as mentioned in issue #1 .

But step by step:
1. Having an optional condition that checks if the api-key flag is true so that it can be accessed.
2. Same thing but for the optional base-url
3. Having the generate_comments potentially take the api-key and or base-url as a argument so that it'd use it, and also a default, whether the default should be done in how it handles arguments or in the function arguments I'm not sure.

**Comment by arilloid** [comment]
Implemented the logic to allow users to specify base URL and api key with option flags.
